name: 'Get Code & run maven code'
description: 'Download code, install dependencies, run Selenium code'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven
      uses: s4u/setup-maven-action@v1.18.0
      with:
        maven-version: '3.9.6'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ runner.os }}-

    - name: Download Selenium Dependencies
      shell: bash
      run: mvn dependency:resolve

    - name: Build and Run Tests with Maven
      shell: bash
      run: mvn clean test

    - name: Echo Username
      shell: bash
      run: echo "${{ env.FB_UserName }}"

    - name: Print Password
      shell: bash
      run: echo "${{ env.FB_PassWord }}"
