name: Selenium Project PUSH job

on:
  push:
    branches:
      - master  # Change this to your default branch if needed

jobs:
  run-test:
    name: Run Selenium Tests
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust if your project uses a different version

      - name: Set up Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          maven-version: '3.9.6'

      - name: Download Selenium Dependencies
        run: mvn dependency:resolve

      - name: Build and Run Tests with Maven
        run: mvn clean test

      - name: Upload Emailable Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/emailable-report.html
