name: Selenium Project PUSH job

on:
  push:
    branches:
      - master

env:
  FB_UserName: ${{ secrets.FB_USERNAME }}
  FB_PassWord: ${{ secrets.FB_PASSWORD }}

jobs:
  run-test:
    name: Run Selenium Tests
    runs-on: windows-latest
    steps:
      - name: Get code and execute
        uses: ./.github/actions
      - name: Upload Emailable Report
        if: success() && steps.execute-tests.outcome != 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/emailable-report.html
          
  echo-job:
    name: Echo Job
    needs: run-test
    runs-on: windows-latest
    steps:
      - name: Print echo
        run: |
          echo "Dinesh Pallagani"
          echo "Rakesh Pallagani"   

  third-job:
    name: Reuse Workflow
    needs: echo-job
    uses: ./.github/workflows/second-push-job.yml  # Must be a reusable workflow with `on: workflow_call`
