name: Selenium Project PUSH job

on:
  push:
    branches:
      - master

env:
  FB_UserName: ${{ secrets.FB_USERNAME }}
  FB_PassWord: ${{ secrets.FB_PASSWORD }}

jobs:
  run-test:
    name: Run Selenium Tests
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get code and execute
        uses: ./.github/actions/cached-dependencies

      - name: Upload Emailable Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: target/surefire-reports/emailable-report.html

  echo-job:
    name: Echo Job
    needs: run-test
    runs-on: windows-latest
    steps:
      - name: Print echo
        run: |
          echo "Dinesh Pallagani"
          echo "Rakesh Pallagani"

  third-job:
    name: Reuse Workflow
    needs: echo-job
    uses: ./.github/workflows/second-push-job.yml
